FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge

RUN apk update && apk add --no-cache python3

RUN apk update && apk add --no-cache --virtual .build-deps \
    build-base \
    python3-dev \
    dbus-dev \
    glib-dev \
    py3-pip \
    py3-wheel \
    py3-setuptools && \
    pip3 install --no-cache-dir mdns-publisher && \
    apk del .build-deps

COPY start.sh start.sh

CMD ["sh","start.sh"]
