{
 "title": "Sensiron SGP30",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "eCO2",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_eco2_ppm[1m])",
     "legendFormat": "{{valid}}"
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_eco2_ppm[1m])",
     "legendFormat": "{{valid}}"
    }
   ]
  },
  {
   "title": "Total VOC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_tvoc_ppb[1m])",
     "legendFormat": "{{valid}}"
    }
   ]
  },
  {
   "title": "Total VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_tvoc_ppb[1m])",
     "legendFormat": "{{valid}}"
    }
   ]
  },
  {
   "title": "Readings/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sgp_received_packets[1m]))"
    }
   ]
  },
  {
   "title": "Time remaining until acclimated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sgp_seconds_until_acclimated)"
    }
   ]
  },
  {
   "title": "Hydrogen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(sgp_h2_ppm[1m])" }
   ]
  },
  {
   "title": "Ethanol",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_ethanol_ppm[1m])"
    }
   ]
  },
  {
   "title": "Absolute humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_absolute_humidity[1m])"
    }
   ]
  }
 ]
}