{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_temperature[1m])",
     "legendFormat": "Celsius"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_relative_humidity[1m])*100",
     "legendFormat": "%RH"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_absolute_humidity[1m])",
     "legendFormat": "%RH"
    }
   ]
  },
  {
   "title": "Particle counts",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": {
    "defaults": {
     "unit": "particles per decilitre (p/0.1L)"
    }
   },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particle_counts[1m])",
     "legendFormat": "{{microns_lower_bound}}μm"
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_eco2_ppm{valid=\"valid\"}[1m])",
     "legendFormat": "{{valid}} reading"
    }
   ]
  },
  {
   "title": "Total VOC",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sgp_tvoc_ppb{valid=\"valid\"}[1m])",
     "legendFormat": "{{valid}} reading"
    }
   ]
  },
  {
   "title": "Particulate matter concentration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particulate_matter_environmental[24h])*100",
     "legendFormat": "{{microns}}μm"
    }
   ]
  }
 ]
}