{
 "title": "Asair AHT20",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_temperature[1m])"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(aht_temperature[1m])  ",
     "legendFormat": "{{microns_lower_bound}}um"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_relative_humidity[1m])*100"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg_over_time(aht_relative_humidity[1m])*100"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aht_absolute_humidity[1m])"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    {
     "expr": "avg_over_time(aht_absolute_humidity[1m])"
    }
   ]
  },
  {
   "title": "Readings/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aht_received_packets[1m]))"
    }
   ]
  }
 ]
}