{
 "title": "Plantower PMS5003",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Particle counts",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particle_counts[1m])",
     "legendFormat": "{{microns_lower_bound}}um"
    }
   ]
  },
  {
   "title": "Particle counts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(pms_particle_counts[1m])",
     "legendFormat": "{{microns_lower_bound}}um"
    }
   ]
  },
  {
   "title": "PM environmental",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particulate_matter_environmental[24h])",
     "legendFormat": "{{microns}}um"
    }
   ]
  },
  {
   "title": "PM environmental",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particulate_matter_environmental[24h])",
     "legendFormat": "{{microns}}um"
    }
   ]
  },
  {
   "title": "PM standard",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particulate_matter_standard[24h])",
     "legendFormat": "{{microns}}um"
    }
   ]
  },
  {
   "title": "PM standard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg_over_time(pms_particulate_matter_standard[24h])",
     "legendFormat": "{{microns}}um"
    }
   ]
  },
  {
   "title": "Readings/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pms_received_packets[1m]))"
    }
   ]
  }
 ]
}