global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: node_exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: plantower-pms5003-exporter
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 900ms
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["plantower-pms5003-exporter:9100"]
  - job_name: asair-aht20-exporter
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 900ms
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["asair-aht20-exporter:9100"]
